#!/usr/bin/env python3
'''
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
'''

from itertools import takewhile

from fibonacci import fibonacci


if __name__ == '__main__':
    print(sum(takewhile(lambda x: x < 4000000,
                        (n for n in fibonacci() if n % 2 == 0))))
