#!/usr/bin/env python3
'''
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
'''

from sys import argv

from fibonacci import fibonacci


if __name__ == '__main__':
    try:
        limit = int(argv[1])
    except IndexError:
        limit = 4000000

    print(sum(n for n in fibonacci.range(limit - 1) if n % 2 == 0))
